from pprint import pprint
from pysapsso2.sapticket import SapTicket

TICKET_B64 = (
    "AjQxMTABAAdTQVBVU0VSAgADMDAwAwADU0FQBAAMMjAyMzEyMTcxNTI2BwAEAAAAAgg"
    "AAQEJAAFFDwADMTAwEAADRVJQIAARcG9ydGFsOlBPUlRBTFVTRVKIABNiYXNpY2F1dGhlbnRpY2F0aW9u/"
    "wEPMIIBCwYJKoZIhvcNAQcCoIH9MIH6AgEBMQswCQYFKw4DAhoFADALBgkqhkiG9w0BBwExgdowgdcCAQE"
    "wLDAUMRIwEAYDVQQDDAlweXNhcHNzbzICFGPryGuFRXcXwuhDPK0doq80D2kwMAkGBSsOAwIaBQCgXTAYB"
    "gkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0yMzEyMTcxNTI2MjZaMCMGCSqGSIb"
    "3DQEJBDEWBBTzwTt/ak50JWrl39YsNigNIw78HjAJBgcqhkjOOAQDBC8wLQIVAJhQUSOFJk0GYB6Cs8X/u"
    "AnCU7XKAhQtdVkbekMu9rYLVFHOByXChZDVXA=="
)
ticket = SapTicket.from_b64(TICKET_B64)
pprint(ticket)